apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  labels:
    app: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      name: delivery-service
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: 744958734165.dkr.ecr.us-east-1.amazonaws.com/delivery-service:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8998
              protocol: TCP
          envFrom:
            - configMapRef:
                name: synthesis-cm
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  labels:
    app: delivery-service
spec:
  type: NodePort
  selector:
    app: delivery-service
  ports:
    - protocol: TCP
      port: 8998
      targetPort: 8998
      nodePort: 30083
