apiVersion: apps/v1
kind: Deployment
metadata:
  name: dq-service
  labels:
    app: dq-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dq-service
  template:
    metadata:
      name: dq-service
      labels:
        app: dq-service
    spec:
      containers:
        - name: dq-service
          image: 744958734165.dkr.ecr.us-east-1.amazonaws.com/dq-service:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: synthesis-cm
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: dq-service
  labels:
    app: dq-service
spec:
  type: NodePort
  selector:
    app: dq-service
  ports:
    - protocol: TCP
      port: 8999
      targetPort: 8080
      nodePort: 30083
