apiVersion: apps/v1
kind: Deployment
metadata:
  name: harmonization-service
  labels:
    app: harmonization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harmonization-service
  template:
    metadata:
      name: harmonization-service
      labels:
        app: harmonization-service
    spec:
      containers:
        - name: harmonization-service
          image: 744958734165.dkr.ecr.us-east-1.amazonaws.com/harmonization-service:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8998
              protocol: TCP
          envFrom:
            - configMapRef:
                name: synthesis-cm
      restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  name: harmonization-service
  labels:
    app: harmonization-service
spec:
  type: NodePort
  selector:
    app: harmonization-service
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 8998
      nodePort: 30085
