apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  labels:
    app: ingestion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      name: ingestion-service
      labels:
        app: ingestion-service
    spec:
      containers:
        - name: ingestion-service
          image: rahilk82/ingestion-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8998
              protocol: TCP
          envFrom:
            - configMapRef:
                name: app-config
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  labels:
    app: ingestion-service
spec:
  type: NodePort
  selector:
    app: ingestion-service
  ports:
    - protocol: TCP
      port: 8998
      targetPort: 8998
      nodePort: 30080
