apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-service
  labels:
    app: provider-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-service
  template:
    metadata:
      name: provider-service
      labels:
        app: provider-service
    spec:
      containers:
        - name: provider-service
          image: 744958734165.dkr.ecr.us-east-1.amazonaws.com/provider-service:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8998
              protocol: TCP
          envFrom:
            - configMapRef:
                name: synthesis-cm
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: provider-service
  labels:
    app: provider-service
spec:
  type: NodePort
  selector:
    app: provider-service
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 8998
      nodePort: 30083
