name: "rahil-portfolio"
namespace: "synthesis"

imageVersion: "744958734165.dkr.ecr.us-east-1.amazonaws.com/translation-service"

replicaCount: 1

image:
  tag: "1"

restartPolicy: "Always"
containerPort: 80

resources:
  requests:
    cpu: "200m"
    memory: "100Mi"
  limits:
    cpu: "300m"
    memory: "200Mi"

configMapName: "synthesis-config"
# secretName: "synthesis"

services:
  name: "portfolio-service"
  type: "NodePort"
  port: 8998
  targetPort: 8998
  nodePort: 8998
  proto: "TCP"