apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.name | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.name | quote }}
    spec:
      restartPolicy: {{ .Values.restartPolicy | quote }}
      containers:
        - name: {{ .Chart.Name | quote }}
          image: {{ .Values.imageVersion }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName | quote }}
            - secretRef:
                name: {{ .Values.secretName | quote }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
